# Generated by Django 5.1.6 on 2025-02-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MP3File',
        ),
    ]
